title:            Aprende con Alf
description:      Sitio web para la enseñanza de Matemáticas y en particular de Estadística
disqus_shortname: aprendeconalf
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:

# Owner/author information
owner:
  name:           Alfredo Sánchez Alberca
  avatar:         foto_alf.jpg
  bio:            "Profesor de Matemáticas en la Universidad San Pablo CEU."
  email:          asalber@gmail.com
  # Enlaces a redes sociales
  twitter:        aprendeconalf
  facebook:
  github:         asalber
  stackexchange:  https://stackexchange.com/users/1506692/alf
  linkedin:       asalber
  instagram:
  flickr:
  tumblr:
  #Para Google Authorship https://plus.google.com/authorship
  #google_plus:   https://plus.google.com/+AlfredoSánchezAlberca
  google_plus:   https://plus.google.com/104904595276070039968

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:  UA-49901858-1
#google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: CEU
    url: http://www.uspceu.com
    external: true
  - title: MiriadaX
    url: http://miriadax.net
    external: true
estadistica:
  - title: Manual de Estadística
    url: /estadistica/manual
  - title: Ejercicios de Estadística
    url: /estadistica/ejercicios
  - title: Exámenes de Estadística
    url: /estadistica/examenes
  - title: Bioestadística con R y rk.Teaching
    url: /estadistica/rkteaching/bioestadistica
  - title: Videotutorial de rk.Teaching
    url: /estadistica/rkteaching/videotutorial
statistics:
  - title: Statistics Manual
    url: /statistics/manual
  - title: Statistics exercises
    url: /statistics/exercises
  - title: Statistics exams
    url: /statistics/exams
r:
  - title: Paquete rk.Teaching
    url: /rkteaching
  - title: Bioestadística con R y rk.Teaching
    url: /estadistica/rkteaching/bioestadistica
  - title: Videotutorial de rk.Teaching
    url: /estadistica/rkteaching/videotutorial
spss:
  - title: Bioestadística con SPSS
    url: /estadistica/spss
  - title: Libro
    url: /estadistica/spss/libro.html
calculo:
  - title: Manual de Cálculo
    url: /calculo/manual
  - title: Ejercicios de Cálculo
    url: /calculo/ejercicios
  - title: Exámenes de Cálculo
    url: /calculo/examenes
derive:
  - title: Cálculo con Derive
    url: /calculo/derive/calculo-derive
excel:
  - title: Excel manual
    url: /office/excel/manual



# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Madrid
future:      true
highlighter: rouge
markdown:    kramdown

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

coderay:
  coderay_wrap:              div
  coderay_line_numbers:      inline
  coderay_line_number_start: 1
  coderay_tab_width:         4
  coderay_bold_every:        10
  coderay_css:               style

# Gems
gems: [jekyll-paginate]

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

# Amount of post to show on home page
paginate: 5


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
