title:            Aprende con Alf
description:      Sitio web para el aprendizaje de Matemáticas y en particular de Estadística
disqus_shortname: aprendeconalf
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:

# Owner/author information
owner:
  name:           Alfredo Sánchez Alberca
  avatar:         foto_alf.jpg
  bio:            "Profesor de Matemáticas en la Universidad San Pablo CEU."
  email:          asalber@gmail.com
  # Enlaces a redes sociales
  twitter:        aprendeconalf
  facebook:
  github:         asalber
  stackexchange:  https://stackexchange.com/users/1506692/alf
  linkedin:       asalber
  instagram:
  flickr:
  tumblr:
  #Para Google Authorship https://plus.google.com/authorship
  #google_plus:   https://plus.google.com/+AlfredoSánchezAlberca
  google_plus:   https://plus.google.com/104904595276070039968

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:  UA-49901858-1
#google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
estadistica:
  - title: Manual de Estadística II
    url: /estadistica/manual/
  - title: Ejercicios de Estadística
    url: /estadistica/ejercicios/
  - title: Exámenes de Estadística
    url: /estadistica/examenes/
  - title: Fórmulas de Estadística
    url: /estadistica/formulas/
  - title: Bioestadística con R y rk.Teaching
    url: /estadistica/rkteaching/bioestadistica/
  - title: Videotutorial de rk.Teaching
    url: /estadistica/rkteaching/videotutorial/
statistics:
  - title: Statistics Manual
    url: /statistics/manual/
  - title: Statistics exercises
    url: /statistics/exercises/
  - title: Statistics exams
    url: /statistics/exams/
  - title: Statistics cheat sheets
    url: /statistics/cheatsheets/
r:
  - title: Paquete rk.Teaching
    url: /rkteaching/
  - title: Bioestadística con R y rk.Teaching
    url: /estadistica/rkteaching/bioestadistica/
  - title: Videotutorial de rk.Teaching
    url: /estadistica/rkteaching/videotutorial/
python: 
  - title: Manual de Python
    url: /python/manual/
  - title: Ejercicios de Python
    url: /python/ejercicios/
  - title: Exámenes de Python
    url: /python/examenes/
spss:
  - title: Bioestadística con SPSS
    url: /estadistica/spss/
  - title: Libro
    url: /estadistica/spss/libro.html
calculo:
  - title: Manual de Cálculo
    url: /calculo/manual/
  - title: Ejercicios de Cálculo
    url: /calculo/ejercicios/
  - title: Exámenes de Cálculo
    url: /calculo/examenes/
  - title: Fórmulas de Cálculo
    url: /calculo/formulas/  
calculus:
  - title: Calculus Manual
    url: /calculus/manual/
  - title: Calculus exercises
    url: /calculus/exercises/
  - title: Calculus exams
    url: /calculus/exams/
  - title: Calculus cheat sheets
    url: /calculus/cheatsheets/
geogebra:
  - title: Cálculo con Geogebra
    url: /calculo/geogebra/calculo-geogebra/
  - title: Calculus with Geogebra
    url: /calculus/geogebra/calculus-geogebra/
derive:
  - title: Cálculo con Derive
    url: /calculo/derive/calculo-derive/
excel:
  - title: Excel manual
    url: /office/excel/manual/



# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Madrid
future:      true
highlighter: rouge
markdown:    kramdown

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge

# Plugins
plugins: [jekyll-paginate]

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

# Excerpt separator
excerpt_separator: <!--MORE-->

# Amount of post to show on home page
paginate: 5

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
